Change all URIFromDestinationV1 to AddressableFromDestinationV1
knative-sandbox/eventing-kafka-broker pull request #3114
Opened 2023-05-29 22:38 UTC by Leo6Leo

Fixes #3109 

## Proposed Changes

- URIFromDestinationV1 and AddressableFromDestinationV1 are 2 function do the same thing, but their return types are different. URIFromDestinationV1 will only URL string, however, AddressableFromDestinationV1 will return a `Destination` object, which contains more information (e.g CAcert)

**Release Note**

```release-note

```

**Docs**

2023-05-30 07:00 UTC, pierDipi commented
/ok-to-test

2023-05-30 11:28 UTC, Vishal-Chdhry requested changes

2023-05-30 11:28 UTC, Vishal-Chdhry commented on control-plane/pkg/reconciler/consumer/consumer.go
> +			ReplyUrl: destination.URL.String(),
You have to make this change in a few other places as well

https://github.com/knative-sandbox/eventing-kafka-broker/pull/3114/files#diff-6ee4865953a537188757b144b2c85c1d9fb9cf0b206c660216e53289f2e98f2fR155
https://github.com/knative-sandbox/eventing-kafka-broker/pull/3114/files#diff-15d344ea3208a104992f6e8ee1431a4825c26171d1038fac81fddeaa5390bef1R320

2023-05-30 11:35 UTC, Vishal-Chdhry requested changes

2023-05-30 11:35 UTC, Vishal-Chdhry commented on control-plane/pkg/core/config/utils.go
> +		deadLetterSinkURL, err := resolver.AddressableFromDestinationV1(ctx, *delivery.DeadLetterSink, parent)
```suggestion
		deadLetterSinkAddr, err := resolver.AddressableFromDestinationV1(ctx, *delivery.DeadLetterSink, parent)
```

NIT, update variable names, as it is a `addressable` now and not a `URL`

2023-05-30 11:35 UTC, Vishal-Chdhry commented on control-plane/pkg/reconciler/consumer/consumer.go
> +	destination, err := r.Resolver.AddressableFromDestinationV1(ctx, c.Spec.Subscriber, c)
```suggestion
	destinationAddr, err := r.Resolver.AddressableFromDestinationV1(ctx, c.Spec.Subscriber, c)
```

the same change in all other places in `consumer/consumer.go` and `trigger/trigger.go`

2023-05-30 15:05 UTC, Vishal-Chdhry commented
/do-not-test

2023-05-30 15:05 UTC, Vishal-Chdhry commented
/hold

2023-05-30 15:08 UTC, Vishal-Chdhry commented
maybe @pierDipi knows the answer, afaik, tests are run on every pr everytime a change is made, but that should not be a problem. even hold won't stop testing (lgtm will remove the hold)

2023-05-30 15:16 UTC, pierDipi commented
I don't think we can stop it :)

it will run the tests when you push new changes

2023-05-30 15:52 UTC, pierDipi commented
/unhold
/lgtm

2023-05-30 18:53 UTC, pierDipi commented
Yes

/approve

2023-05-30 18:54 UTC, merged

2023-06-01 08:01 UTC, matzew commented
> I don't think we can stop it :)

> it will run the tests when you push new changes

Perhaps "DRAFT" PRs do not have that? But I am not sure, and would not too much worry about that

2023-06-01 14:30 UTC, creydr commented
> I pulled up a draft PR [here](https://github.com/knative-sandbox/eventing-kafka-broker/pull/3123). It seems like some tests are suspended, some tests are still running. @matzew

Usually the Github actions run always. Only the Prow jobs will not run on draft PRs.

2023-06-05 11:56 UTC, pierDipi commented
I'm also not sure if you start with ready PR and then convert to draft (which was the case in this PR), does it stop?