Support protobuf, benchmarks and CM size analysis
knative-sandbox/eventing-kafka-broker pull request #98
Opened 2020-08-13 11:20 UTC by pierDipi

## Proposed Changes

- Support protobuf, benchmarks and CM size analysis

2020-08-13 12:59 UTC, slinkydeveloper commented on data-plane/tests/src/main/java/dev/knative/eventing/kafka/broker/tests/core/ConfigUnmarshalling.java
> +@Fork(value = 1, warmups = 1)
at least 5 warmups are needed

2020-08-13 13:00 UTC, slinkydeveloper commented on data-plane/tests/src/main/java/dev/knative/eventing/kafka/broker/tests/core/ConfigUnmarshalling.java
> +  static {
This static block, together with the alloc of `noBrokers`, should live in a state. If you alloc in a static, the jvm might perform some fancy optimizations on it

2020-08-13 13:01 UTC, slinkydeveloper commented on data-plane/tests/src/main/java/dev/knative/eventing/kafka/broker/tests/core/ConfigUnmarshalling.java
> +  static {
What about encapsulating both in a static method and call this static method in the constructor of state?

2020-08-31 08:00 UTC, slinkydeveloper requested changes

2020-10-05 11:12 UTC, pierDipi commented
Too many conflicts and too many changes happened as of late.
/close

2020-10-05 11:12 UTC, closed without merging